<?php

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5fa11cd03263e',
		'title' => 'US elections',
		'fields' => array(
			array(
				'key' => 'field_5fa11cf677b201',
				'label' => 'DC',
				'name' => 'DC',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 3,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'District of Columbia',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b202',
				'label' => 'VT',
				'name' => 'VT',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 3,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Vermont',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b203',
				'label' => 'MA',
				'name' => 'MA',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 11,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Massachusetts',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b204',
				'label' => 'HI',
				'name' => 'HI',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 4,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Hawaii',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b205',
				'label' => 'NY',
				'name' => 'NY',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 29,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'New York',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b206',
				'label' => 'MD',
				'name' => 'MD',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 10,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Maryland',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b207',
				'label' => 'CA',
				'name' => 'CA',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 55,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'California',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b208',
				'label' => 'RI',
				'name' => 'RI',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 4,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Rhode Island',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b209',
				'label' => 'DE',
				'name' => 'DE',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 3,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Delaware',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2010',
				'label' => 'WA',
				'name' => 'WA',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 12,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Washington',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2011',
				'label' => 'CT',
				'name' => 'CT',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 7,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Connecticut',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2012',
				'label' => 'ME1',
				'name' => 'ME1',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 1,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => 'Maine prvi distrikt',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2013',
				'label' => 'NJ',
				'name' => 'NJ',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 14,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'New Jersey',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2014',
				'label' => 'OR',
				'name' => 'OR',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 7,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Oregon',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2015',
				'label' => 'IL',
				'name' => 'IL',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 20,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Illinois',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2016',
				'label' => 'NM',
				'name' => 'NM',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 5,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'New Mexico',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2017',
				'label' => 'CO',
				'name' => 'CO',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 9,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Colorado',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2018',
				'label' => 'VA',
				'name' => 'VA',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 13,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Virginia',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2019',
				'label' => 'ME',
				'name' => 'ME',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 2,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Maine',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2020',
				'label' => 'NH',
				'name' => 'NH',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 4,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'New Hampshire',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2021',
				'label' => 'MI',
				'name' => 'MI',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 16,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Michigan',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2022',
				'label' => 'WI',
				'name' => 'WI',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 10,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Wisconsin',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2023',
				'label' => 'MN',
				'name' => 'MN',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 10,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Minnesota',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2024',
				'label' => 'NV',
				'name' => 'NV',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 6,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Nevada',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2046',
				'label' => 'NE2',
				'name' => 'NE2',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 1,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Nebraska drugi distrikt',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2025',
				'label' => 'PA',
				'name' => 'PA',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 20,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Pennsylvania',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2026',
				'label' => 'AZ',
				'name' => 'AZ',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 11,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Arizona',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2028',
				'label' => 'FL',
				'name' => 'FL',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 29,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Florida',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2029',
				'label' => 'NC',
				'name' => 'NC',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 15,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Sjeverna Carolina',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2030',
				'label' => 'ME2',
				'name' => 'ME2',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 1,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Maine drugi distrikt',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2031',
				'label' => 'GA',
				'name' => 'GA',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 16,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Georgia',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2032',
				'label' => 'IA',
				'name' => 'IA',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 6,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Iowa',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2032',
				'label' => 'OH',
				'name' => 'OH',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 18,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Ohio',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2033',
				'label' => 'TX',
				'name' => 'TX',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 38,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Texas',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			
			array(
				'key' => 'field_5fa11cf677b2034',
				'label' => 'MT',
				'name' => 'MT',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 3,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Montana',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2035',
				'label' => 'SC',
				'name' => 'SC',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 9,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Južna Carolina',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2036',
				'label' => 'AK',
				'name' => 'AK',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 3,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Alaska',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2037',
				'label' => 'MO',
				'name' => 'MO',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 10,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Missouri',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),

			array(
				'key' => 'field_5fa11cf677b2038',
				'label' => 'IN',
				'name' => 'IN',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 11,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Indiana',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2039',
				'label' => 'KS',
				'name' => 'KS',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 6,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Kansas',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2040',
				'label' => 'NE1',
				'name' => 'NE1',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 1,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Nebraska prvi distrikt',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2041',
				'label' => 'MS',
				'name' => 'MS',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 6,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Mississippi',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2042',
				'label' => 'UT',
				'name' => 'UT',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 6,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Utah',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2043',
				'label' => 'SD',
				'name' => 'SD',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 3,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Južna Dakota',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2044',
				'label' => 'TN',
				'name' => 'TN',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 11,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Tennessee',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2045',
				'label' => 'NE',
				'name' => 'NE',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 2,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Nebraska',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2046',
				'label' => 'KY',
				'name' => 'KY',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 8,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Kentucky',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2046',
				'label' => 'LA',
				'name' => 'LA',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 8,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Lousiana',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2046',
				'label' => 'AL',
				'name' => 'AL',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 9,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Alabama',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2048',
				'label' => 'ND',
				'name' => 'ND',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 3,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Sjeverna Dakota',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2049',
				'label' => 'ID',
				'name' => 'ID',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 4,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Idaho',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2050',
				'label' => 'AR',
				'name' => 'AR',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 6,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Arkansas',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2051',
				'label' => 'OK',
				'name' => 'OK',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 7,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Oklahoma',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2052',
				'label' => 'WV',
				'name' => 'WV',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 5,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Zapadna Virginia',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2053',
				'label' => 'WY',
				'name' => 'WY',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 3,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Wyoming',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
			array(
				'key' => 'field_5fa11cf677b2054',
				'label' => 'NE3',
				'name' => 'NE3',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5fa11d5177b21',
						'label' => 'Glasova',
						'name' => 'votes',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 1,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5fa11d6977b22',
						'label' => 'Naziv',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Nebraska treći distrikt',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
	'key' => 'field_5fa14e0d5c87a',
	'label' => 'color',
	'name' => 'color',
	'type' => 'radio',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'choices' => array(
		'red' => 'Trump',
		'blue' => 'Biden',
		'none' => 'Nitko',
	),
	'allow_null' => 0,
	'other_choice' => 0,
	'default_value' => 'none',
	'layout' => 'vertical',
	'return_format' => 'value',
	'save_other_choice' => 0,
),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'us-elections',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

endif;
