
server {
  listen 80;
  server_name www.telegram.hr;

  root "/path/to/project_folder"; # Change path to folder with downloaded source
  index index.html;

  access_log off;
  autoindex off;
  charset utf-8;

  location /wp-content/themes/telegram2-desktop/templates/native/readymag-test {
    if (-f $request_filename ) {
      break;
    }

    if ($args ~ "_escaped_fragment_") {
      rewrite ^/wp-content/themes/telegram2-desktop/templates/native/readymag-test/(.+)/$ /snippets/$1.html last;
      rewrite ^/wp-content/themes/telegram2-desktop/templates/native/readymag-test/([.a-zA-Z0-9-_/]+)$ /snippets/$1.html last;
      rewrite ^/wp-content/themes/telegram2-desktop/templates/native/readymag-test/ /snippets/1.html last;
    }

    location = /wp-content/themes/telegram2-desktop/templates/native/readymag-test {
      if ($args ~ "_escaped_fragment_") {
        rewrite ^/wp-content/themes/telegram2-desktop/templates/native/readymag-test /wp-content/themes/telegram2-desktop/templates/native/readymag-test/snippets/1.html last;
      }

      
      return 301 /wp-content/themes/telegram2-desktop/templates/native/readymag-test/;
      
    }

    rewrite ^/wp-content/themes/telegram2-desktop/templates/native/readymag-test/?$ /wp-content/themes/telegram2-desktop/templates/native/readymag-test/index.html last;
    rewrite ^/wp-content/themes/telegram2-desktop/templates/native/readymag-test/[.a-zA-Z0-9-_]+(/(.*))? /wp-content/themes/telegram2-desktop/templates/native/readymag-test/$2 last;

    try_files $uri $uri/;
  }
}
