
server {
  listen 80;
  server_name www.telegram.hr;

  root "/path/to/project_folder"; # Change path to folder with downloaded source
  index index.html;

  access_log off;
  autoindex off;
  charset utf-8;

  location /super1/native/new-year-new-me-specijal {
    if (-f $request_filename ) {
      break;
    }

    if ($args ~ "_escaped_fragment_") {
      rewrite ^/super1/native/new-year-new-me-specijal/(.+)/$ /snippets/$1.html last;
      rewrite ^/super1/native/new-year-new-me-specijal/([.a-zA-Z0-9-_/]+)$ /snippets/$1.html last;
      rewrite ^/super1/native/new-year-new-me-specijal/ /snippets/1.html last;
    }

    location = /super1/native/new-year-new-me-specijal {
      if ($args ~ "_escaped_fragment_") {
        rewrite ^/super1/native/new-year-new-me-specijal /super1/native/new-year-new-me-specijal/snippets/1.html last;
      }

      
      return 301 /super1/native/new-year-new-me-specijal/;
      
    }

    rewrite ^/super1/native/new-year-new-me-specijal/?$ /super1/native/new-year-new-me-specijal/index.html last;
    rewrite ^/super1/native/new-year-new-me-specijal/[.a-zA-Z0-9-_]+(/(.*))? /super1/native/new-year-new-me-specijal/$2 last;

    try_files $uri $uri/;
  }
}
