name: deploy

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: [self-hosted,hr-telegram-main-runner]

    steps:
      - uses: actions/checkout@v3
