name: deploy

on:
  workflow_dispatch:
  push:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: [self-hosted, staging]

    steps:
      - uses: actions/checkout@v3
